{
  "hippo:cms": {
    "sections": {
      "en": {
        "section-documents": "Documents",
        "section-images": "Images",
        "section-files": "Assets",
        "section-configuration": "Document Types"
      }
    }
  }
}